FROM apache/airflow:2.10.5-python3.11

COPY --chown=airflow:root pyproject.toml README.md requirements-airflow.txt /tmp/project/
RUN pip install --no-cache-dir -r /tmp/project/requirements-airflow.txt

COPY --chown=airflow:root src /tmp/project/src
COPY --chown=airflow:root data /tmp/project/data
RUN pip install --no-cache-dir --no-deps /tmp/project
